// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2zjv0f2ZZzaAoNrOB8KaIZEO1wrLURIc',
    appId: '1:569666897000:web:eb5a4243a74cce55cca7dd',
    messagingSenderId: '569666897000',
    projectId: 'fooddeliverytute-1ba6f',
    authDomain: 'fooddeliverytute-1ba6f.firebaseapp.com',
    storageBucket: 'fooddeliverytute-1ba6f.firebasestorage.app',
    measurementId: 'G-88RWQYVGN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-6PO_UhmUf3L2shVTbCJ7r9aVLcHMOc',
    appId: '1:569666897000:android:15eb12a7e9a4a640cca7dd',
    messagingSenderId: '569666897000',
    projectId: 'fooddeliverytute-1ba6f',
    storageBucket: 'fooddeliverytute-1ba6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsII1jMVBjSy_SohfDuEPryohIO45fHk',
    appId: '1:569666897000:ios:9207054d0a6a1a2acca7dd',
    messagingSenderId: '569666897000',
    projectId: 'fooddeliverytute-1ba6f',
    storageBucket: 'fooddeliverytute-1ba6f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjsII1jMVBjSy_SohfDuEPryohIO45fHk',
    appId: '1:569666897000:ios:9207054d0a6a1a2acca7dd',
    messagingSenderId: '569666897000',
    projectId: 'fooddeliverytute-1ba6f',
    storageBucket: 'fooddeliverytute-1ba6f.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2zjv0f2ZZzaAoNrOB8KaIZEO1wrLURIc',
    appId: '1:569666897000:web:4f6d8355347dfef8cca7dd',
    messagingSenderId: '569666897000',
    projectId: 'fooddeliverytute-1ba6f',
    authDomain: 'fooddeliverytute-1ba6f.firebaseapp.com',
    storageBucket: 'fooddeliverytute-1ba6f.firebasestorage.app',
    measurementId: 'G-115T75SMBR',
  );
}
